apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a91d2lcrv-python 
  janus-idp.io/tekton: a91d2lcrv-python
  backstage.io/kubernetes-id: a91d2lcrv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a91d2lcrv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml